#example
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "change-this-now"

url = 'postgresql://neondb_owner:npg_MZsIQ8UpA6PL@ep-blue-silence-ahmnzdca-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
